name: Conventional Commits

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Conventional Commits check
        uses: webiny/action-conventional-commits@v1.3.0
